version: '3'

services:
    db:
        image: mysql:5.7
        container_name: database-container
        restart: always
        tty: true
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        command: --innodb-use-native-aio=0
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=nodedb
        networks:
            - app-db
    app:
        build:
            context: app
        container_name: node
        tty: true
        networks:
            - app-db
            - app-proxy
        entrypoint: dockerize -wait tcp://db:3306 -timeout 30s
        command: "node index.js"
        depends_on:
            - db
    proxy:
        build:
            context: nginx
        container_name: nginx-container
        ports:
            - "8080:80"
        restart: on-failure
        entrypoint: dockerize -wait tcp://node:3000 -timeout 60s /docker-entrypoint.sh nginx -g 'daemon off;'
        depends_on:
            - app
        networks:
            - app-proxy

networks:
    app-db:
        driver: bridge
    app-proxy:
        driver: bridge